name: Generate terraform docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install terraform-docs
        run: |
          curl -sSL https://terraform-docs.io/install.sh | sh install.sh

      - name: Generate README.md
        run: |
          terraform-docs markdown table . > README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Generate terraform docs'
          git push
